const cartActionTypes = {
  TOOGLE_CART_HIDDEN: "TOOGLE_CART_HIDDEN",
  ADD_ITEMS: "ADD_ITEMS",
  REMOVE_ITEMS: "REMOVE_ITEMS",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
};

export default cartActionTypes;
