const ShopActionTypes = {
  FETCH_COLLECTINS_START: "FETCH_COLLECTINS_START",
  FETCH_COLLECTINS_SUCCESS: "FETCH_COLLECTINS_SUCCESS",
  FETCH_COLLECTINS_FAILURE: "FETCH_COLLECTINS_START"
};

export default ShopActionTypes;